neighbours = [
    {"repo": "dani-garcia/vaultwarden", "stargazers": ["SebastianLuebke"]},
    {"repo": "hay-kot/mealie", "stargazers": ["SebastianLuebke"]},
    {"repo": "MichMich/MagicMirror", "stargazers": ["SebastianLuebke"]},
    {"repo": "starlite-api/starlite", "stargazers": ["SebastianLuebke", "vvrubel"]},
    {"repo": "jjlawren/python-plexwebsocket", "stargazers": ["SebastianLuebke"]},
    {"repo": "saltydk/SARotate", "stargazers": ["SebastianLuebke"]},
    {"repo": "l3uddz/cloudplow", "stargazers": ["SebastianLuebke"]},
    {"repo": "vuejs/pinia", "stargazers": ["SebastianLuebke"]},
    {"repo": "karanpratapsingh/system-design", "stargazers": ["SebastianLuebke"]},
    {"repo": "tayler6000/pyVoIP", "stargazers": ["SebastianLuebke"]},
    {"repo": "NyaomiDEV/Sunamu", "stargazers": ["SebastianLuebke"]},
    {"repo": "rdkr/oniongen-go", "stargazers": ["SebastianLuebke"]},
    {"repo": "miguelgrinberg/python-socketio", "stargazers": ["SebastianLuebke"]},
    {"repo": "freeswitch/spandsp", "stargazers": ["SebastianLuebke"]},
    {"repo": "wesleylima/poptoma", "stargazers": ["SebastianLuebke"]},
    {"repo": "markuslindenberg/tc4400_exporter", "stargazers": ["SebastianLuebke"]},
    {"repo": "agronholm/anyio", "stargazers": ["SebastianLuebke"]},
    {"repo": "coturn/coturn", "stargazers": ["SebastianLuebke"]},
    {"repo": "Cloudbox/Cloudbox", "stargazers": ["SebastianLuebke"]},
    {"repo": "flathub/com.icanblink.blink", "stargazers": ["SebastianLuebke"]},
    {"repo": "gnunn1/tilix", "stargazers": ["SebastianLuebke"]},
    {"repo": "gawel/panoramisk", "stargazers": ["SebastianLuebke"]},
    {"repo": "Tautulli/Tautulli", "stargazers": ["SebastianLuebke"]},
    {"repo": "gonicus/gofaxip", "stargazers": ["SebastianLuebke"]},
    {"repo": "django/asgiref", "stargazers": ["SebastianLuebke"]},
    {"repo": "pydantic/pydantic", "stargazers": ["SebastianLuebke", "OlegBugaichuk"]},
    {"repo": "signalwire/freeswitch", "stargazers": ["SebastianLuebke"]},
    {"repo": "mjhea0/awesome-fastapi", "stargazers": ["SebastianLuebke"]},
    {"repo": "Sonarr/Sonarr", "stargazers": ["SebastianLuebke"]},
    {"repo": "syncarr/syncarr", "stargazers": ["SebastianLuebke"]},
    {"repo": "greglandrum/AIDD_RDKit_Tutorial_2021", "stargazers": ["vvrubel"]},
    {"repo": "MolSSI/cookiecutter-cms", "stargazers": ["vvrubel"]},
    {"repo": "samuelcolvin/python-devtools", "stargazers": ["vvrubel"]},
    {"repo": "paperswithcode/releasing-research-code", "stargazers": ["vvrubel"]},
    {"repo": "sriniker/TDT-tutorial-2014", "stargazers": ["vvrubel"]},
    {"repo": "chython/chytorch", "stargazers": ["vvrubel"]},
    {"repo": "chython/chytorch-rxnmap", "stargazers": ["vvrubel"]},
    {"repo": "conda-incubator/conda-lock", "stargazers": ["vvrubel"]},
    {"repo": "pydantic/pydantic-settings", "stargazers": ["vvrubel"]},
    {
        "repo": "PacktPublishing/Building-Data-Science-Applications-with-FastAPI",
        "stargazers": ["vvrubel"],
    },
    {"repo": "flyteorg/flyte", "stargazers": ["vvrubel"]},
    {"repo": "mcs07/docker-postgres-rdkit", "stargazers": ["vvrubel"]},
    {"repo": "ObliviousAI/FastAPI-Enclave-Services", "stargazers": ["vvrubel"]},
    {"repo": "jonra1993/fastapi-alembic-sqlmodel-async", "stargazers": ["vvrubel"]},
    {"repo": "code-specialist/fastapi-keycloak", "stargazers": ["vvrubel"]},
    {"repo": "srush/GPU-Puzzles", "stargazers": ["vvrubel"]},
    {"repo": "testdrivenio/fastapi-sqlmodel-alembic", "stargazers": ["vvrubel"]},
    {"repo": "kuelumbus/rdkit-pypi", "stargazers": ["vvrubel"]},
    {"repo": "scionoftech/FastAPI-Full-Stack-Samples", "stargazers": ["vvrubel"]},
    {"repo": "michaldev/fastapi-async-mongodb", "stargazers": ["vvrubel"]},
    {"repo": "apache/airflow", "stargazers": ["vvrubel"]},
    {"repo": "milvus-io/milvus", "stargazers": ["vvrubel"]},
    {"repo": "airflow-plugins/Example-Airflow-DAGs", "stargazers": ["vvrubel"]},
    {"repo": "Tinkoff/invest-python", "stargazers": ["vvrubel"]},
    {"repo": "tiangolo/odmantic", "stargazers": ["vvrubel"]},
    {"repo": "tiangolo/full-stack-fastapi-postgresql", "stargazers": ["vvrubel"]},
    {"repo": "alan-turing-institute/the-turing-way", "stargazers": ["vvrubel"]},
    {"repo": "volkamerlab/teachopencadd", "stargazers": ["vvrubel"]},
    {"repo": "oddt/oddt", "stargazers": ["vvrubel"]},
    {"repo": "OlegBugaichuk/dl-academy-app", "stargazers": ["OlegBugaichuk"]},
    {"repo": "sqlalchemy/alembic", "stargazers": ["OlegBugaichuk"]},
    {
        "repo": "alexey-goloburdin/django-clean-template",
        "stargazers": ["OlegBugaichuk"],
    },
    {"repo": "cosmicpython/book", "stargazers": ["OlegBugaichuk"]},
    {"repo": "alexey-goloburdin/thanks", "stargazers": ["OlegBugaichuk"]},
    {"repo": "tiangolo/mypy", "stargazers": ["OlegBugaichuk"]},
    {"repo": "tiangolo/uvicorn", "stargazers": ["OlegBugaichuk"]},
    {"repo": "tiangolo/sqlalchemy", "stargazers": ["OlegBugaichuk"]},
    {"repo": "tiangolo/starlette", "stargazers": ["OlegBugaichuk"]},
    {"repo": "tiangolo/pydantic", "stargazers": ["OlegBugaichuk"]},
    {"repo": "python-poetry/poetry", "stargazers": ["OlegBugaichuk"]},
    {"repo": "sqlalchemy/sqlalchemy", "stargazers": ["OlegBugaichuk"]},
    {"repo": "tiangolo/fastapi", "stargazers": ["OlegBugaichuk"]},
    {"repo": "acherkashin/yandex-music-extension", "stargazers": ["OlegBugaichuk"]},
]
